DO
$$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_roles
    WHERE rolname = '__KEYCLOAK_DB_USER__'
  ) THEN
    CREATE ROLE __KEYCLOAK_DB_USER__ LOGIN PASSWORD '__KEYCLOAK_DB_PASSWORD__';
  END IF;
END
$$;

ALTER ROLE __KEYCLOAK_DB_USER__ WITH LOGIN PASSWORD '__KEYCLOAK_DB_PASSWORD__';

SELECT 'CREATE DATABASE __KEYCLOAK_DB_NAME__ OWNER __KEYCLOAK_DB_USER__'
WHERE NOT EXISTS (
  SELECT 1
  FROM pg_database
  WHERE datname = '__KEYCLOAK_DB_NAME__'
)\gexec

ALTER DATABASE __KEYCLOAK_DB_NAME__ OWNER TO __KEYCLOAK_DB_USER__;
GRANT ALL PRIVILEGES ON DATABASE __KEYCLOAK_DB_NAME__ TO __KEYCLOAK_DB_USER__;
